### ISSUE TITLE
Add guides how to update Lisk Core

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1026]
Add 3 new guides which explain how to update the different distributions of Lisk Core

- [x] Binary #1209 
- [x] NPM #1210 
- Snap [paused until update of the snap channels] #1215 
- [x] Source #1211

**Comment by ManuGowda** [comment]
Binary:
1. Download new updates:
   - wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz
   - wget https://downloads.lisk.io/lisk/test/3.0.2/lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
   - sha256sum -c lisk-core-v3.0.2-linux-x64.tar.gz.SHA256
2. Extract
   - tar xf lisk-core-v3.0.2-linux-x64.tar.gz
3. If configured using pm2
   - pm2 stop lisk-core
   - pm2 start lisk-core
4. Enable forging
   - lisk-core forging:enable address x x x

This is what I follow, maybe @fchavant and @Nazgolze can give some inputs as well.

**Comment by ghost** [comment]
> 2. Extract
>    
>    * tar xf lisk-core-v3.0.2-linux-x64.tar.gz
> 3. If configured using pm2
>    
>    * pm2 stop lisk-core
>    * pm2 start lisk-core

You should to stop (old) lisk-core before unpacking the tarball of the new version. It might make sense to move the old installation to have a backup. A backup of `~/.lisk/` can't hurt either.

**Comment by mrv777** [comment]
I would like to leave a few comments on what I currently see.

1. When doing a backup, do we want to include `node_modules` folder?  There are a lot of files in there and slows the backup process greatly.
2. Delegates that use the binary install may have the `custom-config.json` file in the `lisk-core` folder that will be removed.  It may be good to back that up separately to add it back easily/quickly after upgrading, or at least extract the delegate information there and import it into a new config file based off the example provided in the new release
3. Does these steps also delete the blockchain, making it so the upgrade has to sync from the 3.x genesis block again?
