### ISSUE TITLE
Elements usage formatting issue

### ISSUE THREAD

**Issue by renekorss** [LiskArchive/lisk-legacy-docs#116]
https://lisk.io/documentation/lisk-elements/packages/constants

Usage example dosen't have "line breaks", see image below.

![elements-usage](https://user-images.githubusercontent.com/1494080/48757471-87637000-eca5-11e8-9889-e63de9a6add9.png)

Markdown preview looks good.  I would fix it if I would know how it is finally compiled to HTML. Currently can't test any changes.

**Comment by Tschakki** [comment]
Hi @renekorss,

thanks for spotting this! We have fixed it on the website :)
