### ISSUE TITLE
Create new guide: How to create and sign transactions offline

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1164]
A new guide that explains how to sign transactions in a complete offline environment.

**Comment by ManuGowda** [comment]
If we can cover the following items, would be nice.
- Create transaction online/offline
    - Sign online
    - Sign offline
       - Provide links to all the required asset schema (for lisk-core transactions)
       - Provide links to get networkIdentifier based on network (testnet/mainnet, etc..)
       - Provide token transfer example
