### ISSUE TITLE
Add details on how to use lisk-sdk on Windows

### ISSUE THREAD

**Issue by cindyc-dev** [LiskArchive/lisk-legacy-docs#1183]
Mention and/or link to WSL (Windows Subsystem for Linux) and Docker. Maybe add a short explanation on how to get one or both of these up and running, along with guides for common errors.

### Additional information

https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by Tschakki** [comment]
Thanks @chuahxinyu , WSL looks very interesting!
Still, I hesitate to add it to our documentation, as Windows with WSL is not officially supported or tested.
But I think it's already useful to have a dedicated guide in the Dev forum, so I created it here: https://dev.lisk.com/t/how-to-develop-with-the-lisk-sdk-on-windows-with-wsl-and-vscode/596

Let me know over there if you have any further feedback :)
