### ISSUE TITLE
More detailed descriptions for enabling forging securely without forger_info data

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1216]
### Description
More detailed descriptions for enabling forging securely without forger_info data
- how to obtain finalizedBlock.header.timestamp
- explain what is parent block: `Obtain a block parentBlock which is a parent block of finalizedBlock`

### URL
https://lisk.com/documentation/lisk-core/management/forging.html#safely-enabling-forging-without-forger_info-data

**Comment by Madhulearn** [comment]
Not relevant anymore
