### ISSUE TITLE
Describe `dataAccess` on the plugin intro page

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1233]
### Description
Describe `dataAccess` on the plugin intro page.

### Additional information
This is already described at https://lisk.com/documentation/lisk-sdk/introduction/modules.html#dataaccess, however, the same description should be included on the plugin intro page.

**Comment by shuse2** [comment]
Closing because `dataAccess` is no longer exposed in SDK v6
