### ISSUE TITLE
Explain the different Devnets

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1243]
### Description
Describe how simple it is to setup a local Devnet.
Talk deeper about the different ways how to create a devnet for development (using lisk init or the provided genesisblog and config for devnet), also mention passphrase for the genesis account 

### Motivation
When I use lisk init with Lisk-Commander, it says that it is using the local devnet in docs, but the parameters being passed in app.ts aren’t genesisBlockDevnet or configDevnet so is it still running in devnet?

---

And another one: who can help me with the faucet plugin? The "receive" button is not clickable ... and also the "Faucet address" does not display anything.... Since I am using the genesisBlockDevnet, all registered accounts start with balance=0 . Might this be the reason, because obviously the faucet account also has a 0 balance

**Comment by shuse2** [comment]
This should be explained in #1297 with the section `Update Building a blockchain application`
