### ISSUE TITLE
New guide/tutorial: How to change the token prefix from LSK to a custom prefix

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1247]
### Description
Explain: Each blockchain app (v5) is natively using their own utility token (unnamed)
- How to change the token prefix from LSK to a custom prefix
- How to create addresses with custom prefix (not ""lsk"")"

### Motivation
This is a common task any sidechain developer would like to do at some point.

### Additional information
https://lisk.com/documentation/lisk-sdk/references/lisk-elements/cryptography.html#getbase32addressfrompublickey you can use custom prefix

The core idea for Lisk is that instead of trying your idea as a smart contract with erc20 tokens to a running chain at Lisk you create your own chain and connect it to the Mainchain hosting the LSK tokens. This comes with the benefit of being able to build much more complex onchain solutions than possible on e.g. Ethereum. But of course even on a sidechain people would want implement something erc20 style for their sidechain. This is also possible and actually quite simple - we've seen people prototyping this in a matter of 3-5 days. There are GitHub projects showcasing this. But what I find more convincing is that a fungible token Module is being developed as we speak by LiskHQ and is going to be included in the next release.

**Comment by shuse2** [comment]
Decision was to use the same address in the ecosystem, so this is will be closed
