### ISSUE TITLE
New guide: How to extend the HTTPAPI plugin

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1254]
### Description
A guide that explains how to extend the `HTTPApi` plugin 
Maybe discuss different approaches, of there are
-  creating an additional `HTTPApi` plugin?
- creating an indexer like Lisk Service?

### Motivation
Some people are more familiar with HTTP APIs, so we should provide this guide to show them how they can extend the existing HTTP API

**Comment by shuse2** [comment]
Closing because HTTP API plugin is removed
