### ISSUE TITLE
New guide: How to debit and credit tokens with the reducers of the Token module

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1261]
### Description
Describe how to debit and credit tokens with the reducers of the Token module.

### Additional information

`await reducerHandler.invoke('token:debit', {address, amount})` you can use in a transaction (called transactionAssets in this version) to debit an amount of tokens from the address.

**Comment by shuse2** [comment]
Closing because this will be explained in #1297 
with sections
*  Add Module API (former Reducers)
* Add `How to get & send data to other sidechains`
* Update `Token module`
