### ISSUE TITLE
Hardware requirements for Lisk Service

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1279]
### Description
Describe the minimum hardware requirements to run Lisk Service.

- RAM
- CPU

### Additional information

Alright, it seems like I just needed to increase the memory restart limit, currently it uses 1,7GB and was set to 512MB

it works. But as a word of caution, during the initial tests the LS performance seemed to take a bad hit when I was using separate Droplets (Digital Ocean's equivalent of AWS EC2) even within the same availability zones.

**Comment by MichalTuleja** [comment]
>Alright, it seems like I just needed to increase the memory restart limit, currently it uses 1,7GB and was set to 512MB

Correct, that is absolutely necessary.

> it works. But as a word of caution, during the initial tests the LS performance seemed to take a bad hit when I was using separate Droplets (Digital Ocean's equivalent of AWS EC2) even within the same availability zones.

How were the services distributed? According to my knowledge the only performance-related constraint is to keep Lisk Core and Service Core Microservice on one server. Other microservices can be run on different servers.

**Comment by Tschakki** [comment]
These were comments from users on Lisk chat. Concerning mimimum performance measurements, I would suggest to measure Lisk Service like it is installed the standard way, meaning all services and Core on one server. We can provide additional minimum system requirements only for the gateway service, if required.
