### ISSUE TITLE
API 1.0Which is the correct order, the coin order

### ISSUE THREAD

**Issue by haohaole** [LiskArchive/lisk-legacy-docs#130]
curl -k -H "Content-Type: application/json" \
-X PUT -d '{"secret":"<INSERT SECRET HERE>","publicKey"="<INSERT PUBLICKEY HERE>","delegates":["<INSERT DELEGATE PUBLICKEY HERE>"]}' \
http://localhost:8000/api/accounts/delegates

This is a wrong report.?

**Comment by Tschakki** [comment]
Duplicate of #131
