### ISSUE TITLE
API 1.0 correct coin order? What is the order?

### ISSUE THREAD

**Issue by haohaole** [LiskArchive/lisk-legacy-docs#131]
curl -k -H "Content-Type: application/json" \
-X PUT -d '{"secret":"<INSERT SECRET HERE>","amount":<INSERT AMOUNT HERE>,"recipientId":"<INSERT WALLET ADDRESS HERE>"}' \
http://localhost:8000/api/transactions

It's wrong now？

**Comment by Tschakki** [comment]
The transaction API endpoint changed on Lisk Core v1.0 release.

Please refer to the new documentation: https://lisk.io/documentation/lisk-core/user-guide/api#/Transactions/postTransaction

There you will also find examples and the possibility to send test requests to a testnet node.
