### ISSUE TITLE
Fix inconsistent variable names in guide

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1373]
**Describe the bug**
The code examples use incorrect variable names:

blockBuffer -> blockObject
encodedBlockAsBuffer -> encodedBlockObject

txBuffer ->  txObject
encodedTxAsBuffer -> encodedTxObject

**To Reproduce**
https://lisk.com/documentation/lisk-sdk/guides/app-development/decoding-transactions-blocks.html#decoding-encoding-blocks-and-their-included-transactions

**Comment by NaincyKumariKnoldus** [comment]
Hey @Tschakki Can I do this please if you want?

**Comment by Tschakki** [comment]
Hey @NaincyKumariKnoldus sorry I saw you comment too late, I already created the PR now.

But thanks a lot for the offer 👍 

If you want you can review and leave comments if you have any further remarks :)

**Comment by NaincyKumariKnoldus** [comment]
ok @Tschakki

**Comment by Tschakki** [comment]
Hey again, I already merged the PR now, as I wanted to get the fix ready asap, but if there is anything else that needs to be updated feel free to open a new issue for it :)
