### ISSUE TITLE
Add `Network` page

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1489]
### Description

Create new page explaining the key concepts of the Lisk blockchain.

- This can be taken as a continuation of the network layer explanation.

### ToC

- P2P Network
- Transaction Pool
- Block propagation

### Title

Network

### Nav

`/understand-blockchain/network`

#### Reference material
Blog posts
Lips
Youtube videos
Confluence/Knowledge sharing.

**Comment by TalhaMaliktz** [comment]
**Text from the Understand Lisk Blockchain page**

==== P2P: Unstructured partial mesh network
The P2P network of nodes is unstructured, which means that all nodes are equal participants in the network.
It is also a partial mesh network, therefore every node is only connected to a small subset of nodes in the network.

Unstructured partial mesh networks allow nodes to share information in a very expeditious and secure manner with all other nodes.
In addition, they also have the ability to scale extremely well, even for large networks with thousands of connected nodes.
