### ISSUE TITLE
New page: `Lisk Mainchain DPoS`

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1508]
### Description
Explain how DPoS works in lisk mainchain, and how delegates secure the network.

- Briefly describe how DPoS chooses the delegates
- Explain how user can participate to secure the network by voting
- Explain how delegates will be punished and how it affects the voters

### Motivation
Explaining the security provided by Lisk mainchain is important to ensure for developers that the network they participate is decentralized and secure.

**Comment by Madhulearn** [comment]
Handled in another issue
