### ISSUE TITLE
Update `RPC Endpoints of a Lisk node`

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1513]
### Description
- Explain JSON RPC 2.0 format for usage without API client
- Explain how `method` is derived
- Add HTTP protocol in one of the options
- Explain events cannot be subscribed using HTTP protocol
- Remove `channels`
  - module does not have `channel`
  - plugin `channel` is replaced by API client (ie: no publish)
- Explain how to subscribe (no publish)
- Link to RPC endpoint where SDK expose by default
- Explain how to find information about endpoints for modules SDK provides
  - reference the SDK documentation page
  - link to metadata page

### Motivation

RPC endpoint is the main medium to communicate with a node.

**Comment by Tschakki** [comment]
Additionally, in WS/IPC code example, update `nodeAPIURL` in IPC example with local path and use it in the example, to avoid confusion.

**Comment by TalhaMaliktz** [comment]
The introduction of [RPC Endpoint](https://lisk.com/documentation/understand-blockchain/endpoints.html) needs to be updated. Now a third communication architecture: [HTTP](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol) should be added to the intro.
