### ISSUE TITLE
Add `Aggregate and enhance blockchain data with Lisk Service` page

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1515]
### Description

- Introduction to Lisk Service
- Explain why/when lisk service is needed
  - Explain how Lisk service extends the application created by SDK
- Explain lisk service architecture
- Explain how to add logic to the lisk service
- Add a use case example of how Lisk Service can communicate to other blockchains as well (to comply with being blockchain agnostic).

### Motivation

Lisk Service is also a tool for the developer who creates blockchain applications to provide indexers easily. 

### Location
understand-blockchain

**Comment by Tschakki** [comment]
Will be solved in #1522
