### ISSUE TITLE
Remove `Managing accounts`

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1536]
### Description
- Remove the page as the contents have already been discussed in other parts of the documentation.
- Update navigation
- Remove unused links to the pages.

**Comment by TalhaMaliktz** [comment]
It seems like the file has already been removed in the [PR#741](https://github.com/LiskHQ/lisk-core/pull/741) when the docs were moved to the `lisk-core` repository. The nav is already up to date and no links are present.
