### ISSUE TITLE
Update `RPC API for Lisk nodes`

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1538]
### Description

- Update API for Lisk nodes RPC endpoints request and response
- Add example how to call the RPC API

**Comment by TalhaMaliktz** [comment]
cc: @Tschakki @shuse2 
Data for the following APIs and endpoints are not available yet due to either a bug or work in progress in SDK at the moment, So skipping the following APIs and endpoints until further notice:

- RPC Events
    - network_ready
- RPC Endpoints
    - chain_getEvents
    - chain_proveEvents
    - chain_areHeadersContradicting
    - generator_updateStatus
