### ISSUE TITLE
Update `Application CLI`

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1540]
### Description

- Update Application CLI pallets to be matching with SDK v6

**Comment by TalhaMaliktz** [comment]
The issue [7473](https://github.com/LiskHQ/lisk-sdk/issues/7473) will depreciate the contents of this page to some extent. The content should be revised once the updated information is available.

**Comment by TalhaMaliktz** [comment]
The contents of the Application CLI will be updated again, once the following issues have been resolved at `lisk-sdk`. 
- [Issue # 7526 ](https://github.com/LiskHQ/lisk-sdk/issues/7526)
- [Issue # 7512](https://github.com/LiskHQ/lisk-sdk/issues/7512)
