### ISSUE TITLE
Remove Sequence & Keys module and the HTTP API plugin

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1542]
### Description

- Remove sequence & keys modules docs
- Remove HTTP API plugin docs

**Comment by TalhaMaliktz** [comment]
Hey @shuse2, Should we completely remove the pages and their navigation references for [Key Module](https://lisk.com/documentation/lisk-sdk/modules/keys-module.html), [Sequence Modules](https://lisk.com/documentation/lisk-sdk/modules/sequence-module.html) and [HTTP API Plugin](https://lisk.com/documentation/lisk-sdk/plugins/http-api-plugin.html)?

**Comment by TalhaMaliktz** [comment]
Hey @Tschakki, Is there a ripple effect? or will commenting the content and its nav links will suffice?

**Comment by shuse2** [comment]
Yes, we can completely remove all of them because it does not exist anymore in v6

**Comment by Tschakki** [comment]
Actually, I think the `Keys`  and `Sequence` modules pages are removed already. 

But there are still some places in the documentation linking to them, it would be nice to remove those links as well.

**Comment by TalhaMaliktz** [comment]
Alright, will soft-delete all. Thanks for your input everyone :)
