### ISSUE TITLE
Rectify a Typo on `Create Genesis Block` docs page

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskArchive/lisk-legacy-docs#1567]
### Problem
On the [Create-Genesis-Blockchain ](https://lisk.com/documentation/build-blockchain/create-genesis-block.html)page, there is a bug. The bullet point in the note section says

- “a custom module `NftModule` is created, as explained in the previous guide [Creating a new module](https://lisk.com/documentation/build-blockchain/create-module.html)”

### However, it should be:
- “a custom module `HelloModule` is created, as explained in the previous guide [Creating a new module](https://lisk.com/documentation/build-blockchain/create-module.html)”

<img width="1056" alt="Screenshot 2022-07-22 at 1 16 46 PM" src="https://user-images.githubusercontent.com/13951043/180399886-046f83cd-d013-4979-9ac4-0e3cffc059e2.png">

Affected branch: `main/development`

**Comment by milenagojkovic** [comment]
-
