### ISSUE TITLE
Add `Backups` page for lisk service

### ISSUE THREAD

**Issue by shuse2** [LiskArchive/lisk-legacy-docs#1572]
### Description

Add a page to explain how to backup lisk service node for v0.7.0

### Motivation
After running a lisk node for a while, there will be indexed data in the lisk service similar to `snapshot` in Lisk node.
Lisk service should be able to start from the 'backup' data, and the steps to generate the backup and restore the backup for the lisk service should be explained.

This issue in now being handled in https://github.com/LiskHQ/lisk-service/issues/1751

**Comment by chris529** [comment]
This issue in now being handled in https://github.com/LiskHQ/lisk-service/issues/1751
