### ISSUE TITLE
Update `Application CLI` according to the latest SDK build for v6 

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskArchive/lisk-legacy-docs#1622]
The issue [7473](https://github.com/LiskHQ/lisk-sdk/issues/7473) will depreciate the contents of `sdk/application-cli` page to some extent. The content should be revised once the updated information is available.

_Originally posted by @TalhaMaliktz in https://github.com/LiskHQ/lisk-docs/issues/1540#issuecomment-1236688310_

**Comment by Tschakki** [comment]
Will be solved in #1700
