### ISSUE TITLE
Update SDK/Application CLI

### ISSUE THREAD

**Issue by TalhaMaliktz** [LiskArchive/lisk-legacy-docs#1626]
### Motivation
An earlier Issue #1540 updated the majority of content for **SDK/Application CLI**, however, some commands still need an update as they depend on corresponding issues on the `lisk-sdk` side.

### Description

- Update/Add CLI content and examples for `generator:enable` and `generator:disable` as per [Issue #7526](https://github.com/LiskHQ/lisk-sdk/issues/7526).
- Add CLI example to `node:metadata` as per [Issue #7512](https://github.com/LiskHQ/lisk-sdk/issues/7512).
- Remove/Update account, blskeys and passphrase command as per [Issue # 7473](https://github.com/LiskHQ/lisk-sdk/issues/7473).
- Recheck the content of **SDK/Application CLI** as per [Issue # 7511](https://github.com/LiskHQ/lisk-sdk/issues/7511).
- Distribute commands on separate, yet interconnected pages to improve readability.

#### Affected branch / URL
`docs-sdk`

#### Page location
`lisk-docs/build/docs-sdk/modules/ROOT/pages/application-cli.adoc`

### Additional resources

- [Issue # 7473](https://github.com/LiskHQ/lisk-sdk/issues/7473)
- [Issue # 7512](https://github.com/LiskHQ/lisk-sdk/issues/7512)
- [Issue # 7526](https://github.com/LiskHQ/lisk-sdk/issues/7526)
- [Issue # 7511](https://github.com/LiskHQ/lisk-sdk/issues/7511)

**Comment by Tschakki** [comment]
Will be solved in #1700
