### ISSUE TITLE
Swagger is broken

### ISSUE THREAD

**Issue by nerdvibe** [LiskArchive/lisk-legacy-docs#1682]
### Description
Swagger is broken

### Affected branch / URL
https://lisk.com/documentation/lisk-core/reference/api.html#/

**Comment by Tschakki** [comment]
I think this is referring to the fact that we use the swagger spec from Github to generate the API, so the "Try it out" buttons to post queries to a network are not working anymore. 
We can probably do a quick fix by disabling the `Try it out`-Button in the Swagger UI by setting the option`supportedSubmitMethods = []`

See here: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
