### ISSUE TITLE
Test Docker setup with Lisk core v4.0.0

### ISSUE THREAD

**Issue by chris529** [LiskArchive/lisk-legacy-docs#1696]
When Lisk core v4 image is ready and the beta version is available, then test the Docker set up with lisk-core v4. 

lisk-docs/lisk-core/v4/setup/docker.html

(This issue pertains to the already merged PR Update Docker setup page:  https://github.com/LiskHQ/lisk-docs/pull/1642)

**Comment by Tschakki** [comment]
Solved by https://github.com/LiskHQ/lisk-core/pull/779
