### ISSUE TITLE
Add documentation for Lisk Service 

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#1733]
### Description

The documentation content specific to Lisk Service should be added to the `lisk-service` repository under the `docs/` folder.

### Motivation

Because the content is closely connected and it improves overall management of the Lisk documentation as a whole.

### Acceptance Criteria

- Documentation is up-to-date
- Documentation is programatically generated (where possible)
- Documentation can be rendered on the official website straight from the repo
- Documentation Markdown files are merged with existing ADOC.

### Additional Information

Epic: https://github.com/LiskHQ/lisk-docs/issues/1293

**Comment by MichalTuleja** [comment]
Hi @Tschakki, could you please specify which format and directory structure inside `docs/` shall we apply here?

**Comment by ManuGowda** [comment]
@sameersubudhi we need to discuss this once we are closer to development complete

**Comment by Tschakki** [comment]
As discussed with @sameersubudhi, we will not move the Lisk Service 0.6 docs, and will create the 0.7 docs directly in the Lisk Service repository.
