### ISSUE TITLE
Update path for logrotate

### ISSUE THREAD

**Issue by punkrock** [LiskArchive/lisk-legacy-docs#175]
As the path for the log-files has changed, it needs to be updated in [this doc](https://lisk.io/documentation/lisk-core/setup/install/binary). Also, to include files like `lisk.log.1` the new path should be like this:

*Testnet*
`~/lisk-test/logs/testnet/*.log*`

*Mainnet*
`~/lisk-main/logs/mainnet/*.log*`

Example for Testnet:

```
~/lisk-test/logs/testnet/*.log* {
        daily
        rotate 5
        maxage 7
        compress
        delaycompress
        missingok
        notifempty
}
```

**Comment by Tschakki** [comment]
Hi punkrock!
Good spot! But we got this :)
This is already merged for the upcoming core docs release, see #165
