### ISSUE TITLE
Overflowing table in the client config page in the SDK docs v6.0.0

### ISSUE THREAD

**Issue by chris529** [LiskArchive/lisk-legacy-docs#1845]
### Description

In the legacy description of the Client configuration page, the table in the 'Properties' tab is not defined/justified correctly, and overflows into the Contents description on the right hand side of the page. 

### Affected branch / URL
`lisk-sdk/v6/config.adoc#legacy`

**Comment by TalhaMaliktz** [comment]
Duplicate Issue: https://github.com/LiskHQ/lisk-docs/issues/1835
