### ISSUE TITLE
The Generate module under REFERENCES In Lisk Commander needs an update

### ISSUE THREAD

**Issue by kaksv** [LiskArchive/lisk-legacy-docs#1902]
### Location 
[Lisk Documentation --> Lisk SDK -->References -->Lisk Commander -->Commands >Generate Module](https://lisk.com/documentation/lisk-sdk/references/lisk-commander/commands.html#generate-module)

### Description
With *lisk-commander/6.0.0-rc.4* , Whenever I run the command ` generate:module hello 1000 ` , an error: **_Error: Unexpected argument: 1000_** is returned. When i remove the **Id(1000)** , then the generate command is executed successfully.

#### Affected branch / URL
List the branch name which includes the outdated content.
(https://lisk.com/documentation/build-blockchain/create-module.html "first section")
(https://lisk.com/documentation/lisk-sdk/references/lisk-commander/commands.html#generate-module "second section")
#### Page location
Insert the path of the affected page(s) in the documentation.
```
https://lisk.com/documentation/build-blockchain/create-module.html
https://lisk.com/documentation/lisk-sdk/references/lisk-commander/commands.html
```

### Additional resources
Relevant resources to solve the issue, i.e. lips, code examples, blogs, videos, documents, etc.
![Screenshot during code execution](https://noretake.com/upload/Screenshot.png "The Screenshot for error and Solution")

**Comment by Tschakki** [comment]
Hey @kaksv!

The link you posted points to the latest version of the Lisk SDK docs, which is the version that is currently deployed on the Lisk Mainnet. 
We have already released the next major version of the Lisk SDK under a beta tag. It is already deployed on the Lisk Testnet currently. Therefore we created an updated version of the Lisk docs, which you can find by changing the version number of the docs in the navigation to the latest beta release: https://lisk.com/documentation/lisk-sdk/v6/index.html
Please note, that the documentation is still work in progress. Currently missing content is added step-by-step.

Same goes for the general documentation, you find the docs for the next major release here: https://lisk.com/documentation/beta/index.html

The current docs will be fully replaced with the beta documentation, once the new version is deployed on the Lisk Mainnet.

**Comment by kaksv** [comment]
Thank you for the reply.
