### ISSUE TITLE
mac install

### ISSUE THREAD

**Issue by benjiqq** [LiskArchive/lisk-legacy-docs#198]
mac install from source and binary is not 100% clear and accurate

`installLisk.sh: line 228: syntax error near unexpected token `>'
`

https://lisk.io/documentation/lisk-core/setup/binary#execute-the-installation-script

**Comment by Tschakki** [comment]
Hi @benjyz !

Mac is not supported for Binary installation, see https://lisk.io/documentation/lisk-core/setup/binary#determine-if-your-platform-can-run-lisk-core

If you want to install Lisk Core on Mac, please install it from Source or with the Docker distribution, see: https://lisk.io/documentation/lisk-core/setup
