### ISSUE TITLE
Add What is Lisk Core video to introduction page

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#20]
Now that we are switching to pure markdown for the content of our documentation,  we cannot include videos directly anymore.

What we can do is including images, so  maybe include a picture of the video that links to youtube.

**Comment by willclarktech** [comment]
Markdown is a superset of html, so we should be able to include videos using html tags.

**Comment by Tschakki** [comment]
Depends if you are allowed to use the html tag. E.g. on github, they won't be rendered, unless we use github pages: https://pages.github.com/
see also: https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md
