### ISSUE TITLE
The whole website is broken.

### ISSUE THREAD

**Issue by serranoarevalo** [LiskArchive/lisk-legacy-docs#246]
![Screen Shot 2019-05-27 at 12 43 00 PM](https://user-images.githubusercontent.com/3612017/58394200-008cb700-807d-11e9-9375-549b34c2c338.png)

Not only docs but also the roadmap just show blank spaces where the content should be.

**Comment by belgianwolfie** [comment]
@serranoarevalo Thanks for reporting this. Would you mind giving us some more info so we can dive in and see if we can reproduce.
You're a coder, you know the drill :)  Browser version , os, etc ...

**Comment by belgianwolfie** [comment]
update on our end (anticipating your specs): Our devops @Nazgolze did a quick check and may have uncovered an issue with our caching mechanisms. As a quick (hopefully) fix, he invalidated the cache which should have fixed the issue you were experiencing.

**Comment by serranoarevalo** [comment]
Fixed!
