### ISSUE TITLE
Improve tutorials

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#262]
- more beautiful file tree
- full code example in step 3
- use Lisk Commander/API for verification instead of db query
- Add instruction: `dropdb lisk_dev && cretedb lisk_dev`
 - add `touch hello_transaction.js`
 - Transaction TYPE: reserve more numbers (0-100 for example)
- Interact with the network:  - add `cd ../client`
 - add `touch create_sendable_transaction_base_trs.js`
 - add `touch print_sendable_hello-world.js`
- add print command before showing the transaction object
 - add `make sure your node is running` in order to send the transaction
 - The tutorial says `/hello-world-app # root directory of the application` but the setup uses `mkdir hello_world`
- The creation of a new instance of an Application does not work with alpha2.1.0-1 with the syntax shown on the readme - this works in stead const app = new Application(genesisBlockDevnet, configDevnet);
- request that participants try and run their blockchain application after stage 2.

**Comment by RachBLondon** [comment]
What do you think about this for the file tree?

```
cashback-app
└───client // currently empty
|
└───server
│   │   node_modules
│   │   package.json
|   |   cashback_transaction.js
│   │   index.js
```
