### ISSUE TITLE
Document database layer

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#271]
Explanations about the database architecture of the Lisk SDK.

Document DB layer, and discuss immutability and trustworthyness of nodes and the data they provide via their API.

### Additional information

rocksDB levelup is used as embedded db

It is not immutable perse I think but if you change your node data to invalid dat for example give your account extra tokens only your node thinks you have it and trying to send it to an exchange will be impossible because other nodes know your real amount of tokens.

---
this could be a problem indeed if you use the permissions offchain. OnChain other node don't accept off chain is always a trust issue of the node (so you should run your own node, if you use it for your business so you know its integrity). And the decentralisation is part of the solution as well, multiple explores for example people can compare the data if they don't have their own trusted node running.

---
mmm so
local db (like rocksdb) is something that each node operator controls, so there is no protection there and it doesnt need the protection.
but the database should be changed only by the block or transaction in normal scenario

---
i mean from API, you could implement exactly the same interface, and return some random thing
and still say you are running a node
this is basically same for any blockchain node (btc/eth etc)
but to be able to prove that the data you provide is correct is important
and that's why we are introducing the state tree in next release

keys are structured different, but otherwise it's all similar
in a way that all key-value bytes pair
but in essence, you cannot trust API endpoint provided others

---
yea, chain state and account state has the same security

**Comment by shuse2** [comment]
Closing because new state model and data usage will be explained in #1495 and #1290
