### ISSUE TITLE
Update status of Applications Registration Transaction to disabled

### ISSUE THREAD

**Issue by janhack** [LiskArchive/lisk-legacy-docs#347]
In Lisk Core 2.0 the  Applications Registration Transaction (type 5) was disabled, but the protocol documentation has not been updated yet.

**Comment by Tschakki** [comment]
This is now updated on branch `docs-protocol`: https://github.com/LiskHQ/lisk-docs/blob/docs-protocol/modules/ROOT/pages/transactions.adoc
