### ISSUE TITLE
Ultra-wide Responsive could be improved

### ISSUE THREAD

**Issue by JesusTheHun** [LiskArchive/lisk-legacy-docs#367]
As you can see in the image attached, the new website does not behave very well on an ultra-wide screen.

This is a 49", 5120x1440 monitor : 

![Screenshot_2019-11-20 Lisk SDK Overview Documentation](https://user-images.githubusercontent.com/94478/69240874-bb65bf80-0b9d-11ea-8376-52eebf8cf3ea.png)

Simply put the content in the center would be a significant improvement.

**Comment by drwm-base** [comment]
Hi could I work on this issue?

**Comment by Tschakki** [comment]
Hi @drwm-base !

Sure you can, contributions are very welcome 👍 

To work on UI related issues, check out the branch `antora` in this repo.
The UI is based on the Antora default UI, see also their docs for reference: https://docs.antora.org/antora-ui-default/

If you start working on it, please assign yourself to the issue, so it is visible to others that someone is already working on it :)

**Comment by Tschakki** [comment]
This is fixed in the latest docs ui bundle
