### ISSUE TITLE
Improve in-page nav dropdown

### ISSUE THREAD

**Issue by belgianwolfie** [LiskArchive/lisk-legacy-docs#402]
**Describe the bug**
As per the other issue about the main nav (https://github.com/LiskHQ/lisk-docs/issues/391) also the "in page nav" dropdown doesn't look optimal.

**To reproduce**
Open site on mobile and click the in page nav down arrow 
![image](https://user-images.githubusercontent.com/1779759/72745738-bb3f6b80-3bb0-11ea-929f-4df809351350.png)

**Comment by Tschakki** [comment]
@belgianwolfie can you elaborate "not optimal"? :)

**Comment by Nazgolze** [comment]
Instead of menu items showing up as

- Menu item 1
- Menu item 2
- Menu item 3

They show up as:
Me
n
u

i
t
e
m

1

M
e
n
u
...

**Comment by belgianwolfie** [comment]
1) Open the in-page submenu on a phone and click on the **"How to build a blockchain application in 3 steps"** > The page jumps to the item but it misses it by a couple of pixels which results in it not showing the title and user feeling lost.

     **solution**: offset your scroll with a couple pixels

2) overall styling issues of which I'll list a couple:
- padding on top and on the sides (in order to keep content away from the edges of the subnav box)
- the styling of the subnav doesnt really feel like a navigation. The main nav looks much better in that sense. Maybe align it more with the main nav.
- no clear way to close the subnav box (other than the obvious clicking outside the box)

**Comment by Tschakki** [comment]
This was removed in the new UI
