### ISSUE TITLE
Export swagger.yml as markdown

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#42]
We need a Markdown version of our API documentation for Lisk Core.

**Comment by Nazgolze** [comment]
## Prerequisistes

### Install swagger2markup-cli

Install [swagger2markup-cli](https://github.com/Swagger2Markup/swagger2markup-cli):
```
curl -O swagger2markup-cli-1.3.3.jar https://bintray.com/swagger2markup/Maven/download_file?file_path=io%2Fgithub%2Fswagger2markup%2Fswagger2markup-cli%2F1.3.3%2Fswagger2markup-cli-1.3.3.jar
curl -O swagger2markup-cli-1.3.3.jar.asc https://bintray.com/swagger2markup/Maven/download_file?file_path=io%2Fgithub%2Fswagger2markup%2Fswagger2markup-cli%2F1.3.3%2Fswagger2markup-cli-1.3.3.jar.asc
gpg --verify swagger2markup-cli-1.3.3.jar.asc
```

### Download JSON from swaggerhub.com

Go to https://app.swaggerhub.com/apis/LiskHQ/Lisk and download "JSON (resolved)" and unzip it:
```
unzip swagger-client-generated.zip
```
This will extract the `swagger.json` file.

## Convert documentation

Ensure `swagger.properties` contains the following:
```
swagger2markup.markupLanguage=MARKDOWN
```

And then run:
```
java -jar swagger2markup-cli-1.3.3.jar convert -i swagger.json -c swagger.properties -f lisk-documentation
```
The documentation in Markdown format will be in `lisk-documentation.md`.

**Comment by Tschakki** [comment]
After discussion with @nazarhussain we decided to not convert the API documentation to markdown, instead we save it as JSON.

This way it is easy to maintain and it does contain all relevant information.
If users want to browse through it with swagger-ui like they are used to, this JSON file can be referenced as source file, e.g. at http://petstore.swagger.io/
