### ISSUE TITLE
NodeJS version mismatch

### ISSUE THREAD

**Issue by JesusTheHun** [LiskArchive/lisk-legacy-docs#442]
This page first table https://lisk.io/documentation/lisk-sdk/setup.html mentions a NodeJs version of EXACTLY 10.15.3.
Later on you can read a suggestion to install `nvm install 10.17.0` -https://lisk.io/documentation/lisk-sdk/setup.html#_node_js

Either make the version requirement flexible or make the command install the correct version.

**Comment by Tschakki** [comment]
This is already updated in the docs for sdk 3.x, so we only need to fix it in `docs-sdk-2.3.7` branch.
