### ISSUE TITLE
Bug in snippet at forging.adoc

### ISSUE THREAD

**Issue by Tschakki** [LiskArchive/lisk-legacy-docs#493]
**Describe the bug**
At https://lisk.io/documentation/lisk-core/management/forging.html 

`lisk passphrase:encrypt --output-public-key` part, should be `lisk passphrase:encrypt --outputPublicKey`

**Comment by chris529** [comment]
Minor typo in code snippet
lisk passphrase:encrypt --output-public-key part, should be lisk passphrase:encrypt --outputPublicKey
