### ISSUE TITLE
1.0 API documentation correction

### ISSUE THREAD

**Issue by Nazgolze** [LiskArchive/lisk-legacy-docs#57]
Previously, it was stated on the api page that the endpoints are preceded by /api.

Binance didn't see it and tried to access http://127.0.0.1:8000/blocks
I gave them the correct one (http://127.0.0.1:8000/api/blocks) and they pointed out the mistake in the docs. I checked and also could not find any mention now of /api/...

**Comment by Tschakki** [comment]
It is were it always was: At beginning of our API documentation, it states:
`[ Base URL: /api ]`
Which is the standard location to display the base path in swagger-ui.
Additionally, they can execute the respective API call inside our documentation, to see a complete example request and it's response.
