### ISSUE TITLE
How to put this documentation online

### ISSUE THREAD

**Issue by Nazgolze** [LiskArchive/lisk-legacy-docs#58]
How is this supposed to happen?

The last that I heard was that the plan was to copy/paste these into Kirby through the panel.

I've also noticed all of the new .md files though and the links to them inside of the markdown files, but Kirby absolutely does not like .md files and will also not create them when you add a page, so if we're planning on copying/pasting any of this through the panel, nearly every single link in the documentation will be a dead link

**Comment by Tschakki** [comment]
Yes, the copy pasting wont go 100% out of the box, unfortunately.
There is no way to make the links work on github and in kirby CMS in the same time.

If we port the changes over, we need to adjust all the links again, and also the file names.
I fear there is no way around it :(
