### ISSUE TITLE
Mention something about Lisk core using SemVer

### ISSUE THREAD

**Issue by jondubois** [LiskArchive/lisk-legacy-docs#62]
It doesn't appear that the docs discuss the Lisk core versioning approach so some users might get confused about version compatibility between nodes. See https://github.com/LiskHQ/lisk/issues/753

We could add a paragraph somewhere to mention that Lisk core follows SemVer conventions; maybe we should also link to an external resource so that the user can read about it in more details.

Maybe this also applies to other projects as well.

**Comment by Tschakki** [comment]
Related issue: LiskHQ/lisk/issues/2594
Related LIP: https://github.com/LiskHQ/lips/blob/master/proposals/lip-0007.md

document new versioning number: protocolVersion
